services:
  app:
    build:
      context: ./serwer
      dockerfile: Dockerfile
    container_name: spring-app-pz
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-default}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    container_name: postgres-db-pz
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${DB_PORT_EXTERNAL:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    image: nginx:alpine
    container_name: frontend-reg-pz
    ports:
      - "${FRONTEND_REG_PORT:-6769}:80"
    volumes:
      - ./frontend_register:/usr/share/nginx/html:ro
    depends_on:
      - app

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
    container_name: admin-panel-pz
    ports:
      - "${ADMIN_PANEL_PORT:-6770}:80"
    depends_on:
      - app

volumes:
  postgres_data:
