spring.application.name=serwer

# Konfiguracja bazy danych (dla lokalnego uruchomienia lub testów)
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:pz_database}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:secret_password}
spring.jpa.hibernate.ddl-auto=update

# Logowanie zapytań HTTP
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.orm.queries=DEBUG
